default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: landing-page_development
  host: localhost
  username: landing
  password: password

test:
  <<: *default
  database: landing-page_test
  host: localhost
  username: landing
  password: password

production:
  <<: *default
  database: landing-page_test
  host: localhost
  username: landing
  password: password
